// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ompvafpbdbwsmelomnla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcHZhZnBiZGJ3c21lbG9tbmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjQ3NDIsImV4cCI6MjA2MTQ0MDc0Mn0.kxbVyt1n0jpqlFHbQqWmuTh-3mfM64-lJ7FqODqoVKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);